version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - TWITCH_CHANNEL=${TWITCH_CHANNEL:-skittishandbus}
      - TARGET_WORDS=${TARGET_WORDS:-fuck}
    volumes:
      - ./:/app
    restart: unless-stopped

  ngrok:
    image: ngrok/ngrok:latest
    ports:
      - "4040:4040"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: http app:8080
    depends_on:
      - app